### ISSUE TITLE
RNCOpenDoc.open Example local Path

### ISSUE THREAD

**Issue by coy102** [capriza/react-native-open-doc#1]
hi, 

can you explain for local path when im using RNCOpenDoc.open()

i got error 

![err2](https://user-images.githubusercontent.com/13234170/44076321-f94f24f8-9fc9-11e8-811c-c63f52542c7f.jpg)
 
my URL

![err1](https://user-images.githubusercontent.com/13234170/44076326-ffecc716-9fc9-11e8-9502-1a9ffba50cdc.jpg)

and my here's my code

`if(configs.FILE_DOCUMENT_OFFICE.includes(rowData.url.split('.').pop())){
      
      RNCOpenDoc.open(rowData.url);
    }`

**Comment by blankg** [comment]
Hi,

For android you need to define a File Provider https://developer.android.com/reference/android/support/v4/content/FileProvider
Note that the authorities should be `<your package name>.provider`:
```
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="com.mydomain.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            ...
</provider>
```

I will update the documentation accordingly.
thanks

**Comment by coy102** [comment]
thanks, i'll wait

**Comment by blankg** [comment]
Documentation is updated now to use file provider

**Comment by R4DIC4L** [comment]
For androidx, it should be androidx.core.content.FileProvider otherwise this error will appear (https://stackoverflow.com/questions/48534293/android-support-v4-content-fileprovider-not-found):

```
Unable to get provider android.support.v4.content.FileProvider: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider"
Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
        at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:613)
        at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
        at androidx.core.content.FileProvider.attachInfo(FileProvider.java:392)
```

Note: I was also missing the meta-data tag:

```
<provider
    android:name="androidx.core.content.FileProvider"
    android:authorities="${applicationId}.fileprovider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/file_paths" />
</provider>
```
