### ISSUE TITLE
Cancelling on android throws "Bad result code: 0" (RESULT_CANCELLED)

### ISSUE THREAD

**Issue by iwikal** [capriza/react-native-open-doc#3]
I think it would make more sense for the api to simply return an empty array of files in this case.

**Comment by iwikal** [comment]
Especially since I don't see any nice way of detecting this except by doing
```js
if (error.toString() === "Bad result code: 0") {
 // everything is fine, do nothing
}
```

**Comment by blankg** [comment]
@iwikal , thank you for your feedback this issue will be fixed in the next version
